version: '3.4'

services:
    app:
        build: .
        volumes:
            # Mount the working directory into the web root,
            # so you can live-edit while running
            - ./:/var/www
        ports:
            # Web server
            - 8080:80

            # Prometheus metrics
            - 2112:2112

            # Health endpoint
            - 2113:2113
        environment:
            APP_ENV: dev

        # Overrides the default entry point to reload the pool after every request
        entrypoint: [ '/usr/local/bin/rr', 'serve', '-d', '-v', '-o', 'http.workers.pool.numWorkers=1', '-o', 'http.workers.pool.maxJobs=1', '-c', './.rr.yaml' ]
